---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Setup powervm repository
  include: nova_install_apt_powervm.yml
  static: no
  when:
    - "'nova_compute' in group_names"
    - "nova_virt_type == 'powervm'"
    - "ansible_pkg_mgr == 'apt'"

- name: Install distro packages
  package:
    name: "{{ nova_package_list }}"
    state: "{{ nova_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr in ['apt', 'zypper']) | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"

- name: Remove known problem packages for the Spice console
  package:
    name: "{{ item }}"
    state: absent
  register: remove_packages
  until: remove_packages|success
  retries: 5
  delay: 2
  with_items: "{{ nova_spice_distro_packages }}"
  when:
    - inventory_hostname in groups['nova_console']
    - nova_console_type == "spice"
  tags:
    - nova-apt-packages
    - nova-spice-apt-packages

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in nova_developer_constraints %}
      {{ item }}
      {% endfor %}
  when:
    - nova_developer_mode | bool
  tags:
    - nova-pip-packages

- name: Install required pip packages
  pip:
    name: "{{ nova_requires_pip_packages }}"
    state: "{{ nova_pip_package_state }}"
    extra_args: >-
      {{ nova_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  tags:
    - nova-pip-packages

- name: Retrieve checksum for venv download
  uri:
    url: "{{ nova_venv_download_url | replace('tgz', 'checksum') }}"
    return_content: yes
  register: nova_venv_checksum
  when:
    - nova_venv_download | bool
  tags:
    - nova-pip-packages

- name: Attempt venv download
  get_url:
    url: "{{ nova_venv_download_url }}"
    dest: "/var/cache/{{ nova_venv_download_url | basename }}"
    checksum: "sha1:{{ nova_venv_checksum.content | trim }}"
  register: nova_get_venv
  when:
    - nova_venv_download | bool
  tags:
    - nova-pip-packages

- name: Remove existing venv
  file:
    path: "{{ nova_bin | dirname }}"
    state: absent
  when:
    - nova_get_venv | changed
  tags:
    - nova-pip-packages

- name: Create nova venv dir
  file:
    path: "{{ nova_bin | dirname }}"
    state: directory
  register: nova_venv_dir
  when:
    - nova_get_venv | changed
  tags:
    - nova-pip-packages

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ nova_venv_download_url | basename }}"
    dest: "{{ nova_bin | dirname }}"
    copy: "no"
  when:
    - nova_get_venv | changed
  notify: Restart nova services
  tags:
    - nova-pip-packages

- name: Install pip packages
  pip:
    name: "{{ nova_pip_packages }}"
    state: "{{ nova_pip_package_state }}"
    virtualenv: "{{ nova_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ nova_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  when:
    - nova_get_venv | failed or nova_get_venv | skipped
  notify: Restart nova services
  tags:
    - nova-pip-packages

- name: Remove python from path first (CentOS, openSUSE)
  file:
    path:  "{{ nova_bin | dirname }}/bin/python2.7"
    state: "absent"
  when:
    - ansible_pkg_mgr in ['yum', 'dnf', 'zypper']
    - nova_get_venv | changed

- name: Update virtualenv path
  command: >
    virtualenv-tools --update-path=auto --reinitialize {{ nova_bin | dirname }}
  when:
    - nova_get_venv | changed
  tags:
    - nova-pip-packages

- include: "consoles/nova_console_{{ nova_console_type }}_install.yml"
  when:
    - "'nova_console' in group_names"
  tags:
    - nova-install
    - nova-novnc-console
    - nova-spice-console

- name: Initialise the upgrade facts
  ini_file:
    dest: "/etc/ansible/facts.d/openstack_ansible.fact"
    section: nova
    option: "{{ item }}"
    value: True
  with_items:
    - "need_service_restart"
    - "need_online_data_migrations"
  when:
    - (nova_get_venv | changed) or
      (nova_venv_dir | changed) or
      (install_packages | changed) or
      (ansible_local is not defined) or
      ('openstack_ansible' not in ansible_local) or
      ('nova' not in ansible_local['openstack_ansible']) or
      ('need_online_data_migrations' not in ansible_local['openstack_ansible']['nova']) or
      ('need_service_restart' not in ansible_local['openstack_ansible']['nova'])

- name: Record the venv tag deployed
  ini_file:
    dest: "/etc/ansible/facts.d/openstack_ansible.fact"
    section: nova
    option: venv_tag
    value: "{{ nova_venv_tag }}"
