---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- name: Restart libvirt-bin
  systemd:
    name: "{{ libvirt_service_name }}"
    state: "restarted"
    daemon_reload: yes

- name: Restart nova services
  systemd:
    name: "{{ item.value.service_name }}"
    state: "restarted"
  with_dict: "{{ nova_services }}"
  register: nova_service_restart
  when:
    - inventory_hostname in groups[item.value.group]
    - "{{ item.value.condition | default(true) }}"

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
  register: nova_nginx_restart
  until: nova_nginx_restart | success
  retries: 5
  delay: 2
  when: inventory_hostname in groups['nova_api_placement']
